#pragma once

#define ERROR_APP_BASE 0x20000000

#define U_ERROR_FILE_NOT_FOUND         (ERROR_APP_BASE + 0x001)
#define U_ERROR_USER_CANCELLED         (ERROR_APP_BASE + 0x002)
#define U_ERROR_FILE_EMPTY             (ERROR_APP_BASE + 0x003)
#define U_ERROR_FILE_TOO_LARGE         (ERROR_APP_BASE + 0x004)
#define U_ERROR_FILE_WRITE_INCOMPLETE  (ERROR_APP_BASE + 0x005)
#define U_ERROR_ENCODING_CONVERSION_FAILED (ERROR_APP_BASE + 0x006)
#define U_ERROR_INVALID_FILE_PATH      (ERROR_APP_BASE + 0x007)
#define U_ERROR_PROCESS_ACCESS_DENIED  (ERROR_APP_BASE + 0x008)
#define U_ERROR_PATTERN_PARSE_FAILED   (ERROR_APP_BASE + 0x009)
#define U_ERROR_MEMORY_QUERY_FAILED    (ERROR_APP_BASE + 0x010)
#define U_ERROR_PATTERN_NOT_FOUND      (ERROR_APP_BASE + 0x011)
#define U_ERROR_STRING_REPLACE_FAILED  (ERROR_APP_BASE + 0x012)
#define U_ERROR_INVALID_PROCESS_SELECTION (ERROR_APP_BASE + 0x013)
#define U_ERROR_MEMORY_READ_FAILED     (ERROR_APP_BASE + 0x014)
#define U_ERROR_MEMORY_WRITE_FAILED    (ERROR_APP_BASE + 0x015)

#define IS_APPLICATION_ERROR(code) ((code) & 0x20000000)
#define IS_SYSTEM_ERROR(code) (!IS_APPLICATION_ERROR(code) && (code) != 0)